export const LOAD_USERS = "LOAD_USERS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS"
export const SELECT_USER = "SELECT_USER";
export const LOGOUT = "LOGOUT";
export const CHANGE_QUESTIONS_DISPLAY_PREFERENCE = "CHANGE_QUESTIONS_DISPLAY_PREFERENCE";
export const VOTE = "VOTE";
export const CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION";
